title: Free Software from kapcom01
description: 
google_analytics: 
show_downloads: false
theme: jekyll-theme-leap-day

github:
  repository_url: https://github.com/kapcom01

gems:
  - jekyll-mentions
